### ISSUE TITLE
which version is correct for CUDA10.1, pytorch1.7.1

### ISSUE THREAD

**Issue by ZacharySha** [open-mmlab/mmcv#1344]
Hello!~
How to set version here~?
pip install mmcv-full=={ }-f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.1/index.html

**Comment by zhouzaida** [comment]
hi @ZacharySha , you can use the following command to install mmcv-full `pip install mmcv-full https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html`. The reason is that mmcv-full is only compiled on PyTorch 1.x.0 because the compatibility usually holds between 1.x.0 and 1.x.1. If your PyTorch version is 1.x.1, you can install mmcv-full compiled with PyTorch 1.x.0 and it usually works well. For example, if your PyTorch version is 1.8.1 and CUDA version is 11.1, you can use the following command to install mmcv-full.
