### ISSUE TITLE
Can we build the whl by ourselves?

### ISSUE THREAD

**Issue by addicter2017** [open-mmlab/mmcv#1475]
**I can't find a proper whl to build mmcv on torch 1.9.1 cuda 11.1 python 3.7**

Hello everyone! I am new to pytorch and I tried to install mmcv on kaggle using the setup,py method on kaggle notebook. It works well but took over 20 minutes. On kaggle, it doesn't save the enviroment, so I have to install mmcv over and over again, which consumes a lot of time. Can someone tell me if there is a possibility that we build the whl on our own or will the official release the whl version that matches the above environment? Thanks in advance!

**Comment by zhouzaida** [comment]
Note that mmcv-full is only compiled on PyTorch 1.x.0 because the compatibility usually holds between 1.x.0 and 1.x.1. If your PyTorch version is 1.x.1, you can install mmcv-full compiled with PyTorch 1.x.0 and it usually works well.

We have provided the pre-built packages for torch1.9.0-cuda11.1-python3.7 and you can install them with the following command.
```
pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
```

Of course, you can build a wheel with `MMCV_WITH_OPS=1 python setup.py bdist_wheel`.

**Comment by addicter2017** [comment]
Thank you so much for your reply! It solved my problem!
