### ISSUE TITLE
import mmcv-config causes matplotlib to return error. 

### ISSUE THREAD

**Issue by RealNewNoob** [open-mmlab/mmcv#1521]
Hi! I found that somehow importing mmcv.utils.config make my matplotlib through error. Here is the code:
`import matplotlib.pyplot as plt`
`from mmcv.utils.config import Config`
`fig, ax = plt.subplots()`
`plt.show()`

This returns the below error:
QObject::moveToThread: Current thread (0x55c2a5da4150) is not the object's thread (0x55c2a8d1ab90).
Cannot move to target thread (0x55c2a5da4150)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/weitao/anaconda3/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Aborted (core dumped)

However, if I did not import mmcv.utils.config, everything is fine. 
I am using matplotlib 3.4.3; matplotlib-inline 0.1.3; mmcv 1.3.13; mmcv-full 1.3.7; Python 3.8.5

**Comment by teamwong111** [comment]
Hi, @RealNewNoob ,  I am sorry for the late reply. I used `matplotlib 3.4.3; matplotlib-inline 0.1.3; mmcv-full 1.3.7; Python 3.8.5` to check but not get any errors. According to your error messages, I think it is maybe a problem with OpenCV which is upstream lib of mmcv. Maybe it is caused by a conflict in any Qt installations on the system with the Qt that is shipped with OpenCV. Therefore, My suggestions are as follows:
1. Please use the unique and latest mmcv as much as possible.
2. Please use the latest opencv-python as much as possible.
3. If you use ssh to run a GUI program, please make X11 forwarding enabled.
