### ISSUE TITLE
Error when using mmcv.ops.DeformRoIPoolPack:  CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by penghaozhou** [open-mmlab/mmcv#419]
Hi, when i use mmcv.ops.DeformRoIPoolPack, i get the following error:
`
File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
File "/usr/local/lib64/python3.6/site-packages/mmcv/ops/deform_roi_pool.py", line 193, in forward
    self.gamma)
File "/usr/local/lib64/python3.6/site-packages/mmcv/ops/deform_roi_pool.py", line 59, in forward
    gamma=ctx.gamma)
RuntimeError: CUDA error: invalid configuration argument
`

My env is pytorch1.5, cuda10.1.
How can I deal with the problem? 
Thanks.

**Comment by yhcao6** [comment]
I guess it is due to your poor GPU. You may decrease the value of `THREADS_PER_BLOCK`.
https://github.com/open-mmlab/mmcv/blob/cac22f8cf5a904477e3b5461b1cc36856c2793da/mmcv/ops/csrc/common_cuda_helper.hpp#L10
It looks you install mmcv with pip, you may have to compile it from source if you change the value of `THREADS_PER_BLOCK`.

**Comment by hellock** [comment]
@yhcao6 Is this documented now?

**Comment by yhcao6** [comment]
> @yhcao6 Is this documented now?

https://github.com/open-mmlab/mmcv/blob/master/docs/trouble_shooting.md
