### ISSUE TITLE
Question about flops counter of pooling layers and bn layers

### ISSUE THREAD

**Issue by CoinCheung** [open-mmlab/mmcv#827]
https://github.com/open-mmlab/mmcv/blob/999f2d08b4daccb73ca4483d3cbe349563ac58a7/mmcv/cnn/utils/flops_counter.py#L424

Hi,

Let me be brief to save your time with my respect: 

1. Shouldn't flops of pool layers be computed in same way as sepconv ?

2. It seems that you did not count the computation of mean/var of the batch when you compute flops of bn layers. Would you tell me why shouldn't consider this ?

**Comment by hellock** [comment]
1. Computing the exact flops of pooling layers may be tricky in terms of different implementations and configurations. Since it is usually quite small compared to other layers, different computations does not make much difference for the whole model.
2. FLOPs are computed in terms of inference, thus the mean/var are already given.
