### ISSUE TITLE
missing optimizer argument in iter_based_runner

### ISSUE THREAD

**Issue by ryoma-k** [open-mmlab/mmcv#936]
validation function in iter_based_runner, the model is called without optimizer.
however in epoch_based_runner, its model is called with optimizer even in validation time iteration.

https://github.com/open-mmlab/mmcv/blob/375605fba8f89f40eb1b6b67b4aab83fbe769098/mmcv/runner/iter_based_runner.py#L77

https://github.com/open-mmlab/mmcv/blob/375605fba8f89f40eb1b6b67b4aab83fbe769098/mmcv/runner/epoch_based_runner.py#L32

I'm not familiar with mmcv and I'm not sure if this is kind of bug, but when using [mmdetection](https://github.com/open-mmlab/mmdetection) error occurred here.

https://github.com/open-mmlab/mmdetection/blob/5ebba9a9221c3f6f8754d4efe293cdcd12be8dd4/mmdet/models/detectors/base.py#L255

I doubt if we should pass optimizer in validation step but this fix can be helpful at least in mmdetection, right?

**Comment by ryoma-k** [comment]
or just adding this is not enough? #639?

**Comment by zhouzaida** [comment]
hi, @ryoma-k , thanks for your feedback. In fact, the `optimizer` in `train_step()` or `val_step()` will not be used in many downstream repos because we have a  optimizer hook for `optimizer.step()` except `mmediting`.

https://github.com/open-mmlab/mmediting/blob/3c26d348b00958e972cf7b5ed5500a171b5f5e02/mmedit/models/inpaintors/deepfillv1.py#L258

**Comment by ryoma-k** [comment]
got it. anyway thanks!
